# Generated by Django 4.2.10 on 2026-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
