# Generated by Django 4.2.10 on 2026-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wrong_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
