# Generated by Django 4.2.10 on 2026-03-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_lock_until_userprofile_wrong_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_color',
            new_name='favorite_food',
        ),
    ]
